### PR TITLE
updated socket-io to 0.7.9

### PR DESCRIPTION
**Pull request by fwoeck**
Hi Alex,

I just updated the socket-io dependency to 0.7.9. Checks with FF36 (Win, FlashSocket), Safari 5.1 (Osx), Chrome 13 (Win32, Osx) and IE9 passed for me.

--Frank

### CODE REVIEW

**Comment by dvdplm** [comment]
Upgrading to Socket.IO@0.7.9 fixes the "blows up on client disconnect" issue for me, but Chrome v15.0.854.0 (dev) still can't establish a WebSocket (and no fallback transport is activated).

**Comment by fwoeck** [comment]
Hi, can you try starting the juggernaut server with

env NODE_ENV=production /path/to/juggernaut

I added a config snippet to the server in this pull request that enables FlashSockets in prod-mode.
Can you retry Chrome dev with it?

--Frank

**Comment by dvdplm** [comment]
Tried, but no luck. Setting it to xhr-polling for now, sucks but works in all the browsers I'm using. Weirdly enough I got the same error using Chrome v14. Thanks for the suggestion!

David

**Comment by iros** [comment]
This fixed the crash issue for me as well. Any chance this could be pulled? I'm running from fwoeck's branch...

**Comment by iros** [comment]
dvdplm, the chrome dev version is an actual socket.io issue. You can keep an eye on it here: https://github.com/LearnBoost/socket.io/issues/429

**Comment by fwoeck** [comment]
The new 0.8.2 version solves an issue with Firefox 6.
Websockets didn't work anymore because Mozilla renamed the interface from WebSocket to MozWebSocket.

--Frank

**Comment by fwoeck** [comment]
@0.8.2: the client for 0.8.2 actually doesn't work with ff6, see https://github.com/LearnBoost/socket.io-client/issues/287
But this can easily fixed by replacing line 2249 in socket_io.js by

return window.MozWebSocket || window.WebSocket;

--Frank

**Comment by fwoeck** [comment]
another patch is necessary - see https://github.com/LearnBoost/socket.io-client/issues/287

**Comment by iros** [comment]
@fwoeck - thanks for the hard work. I've been forking off of your fork while waiting for this to get pulled in to juggernaut proper.

**Comment by fwoeck** [comment]
@iros: I'll update my fork frequently because we use juggernaut2 in our project. There's only two things I changed really:

i) the dependency node-static-maccman was replaced by node-static to make it updatable. I think, the reason for Alex to modify the original module in the first place was to be able to deliver the FlashSocket swf file separately, which is obsolete in the latest socket.io-version.

ii) I added a small production environment configuration to silence the logs and make FlashSockets work, see my comment from august 17.

--Frank

**Pull request closed without merging**
