### PR TITLE
Fix for broken subscribe method in Ruby library

### PR DESCRIPTION
**Pull request by mikedemers**
The code in "client/examples/roster.rb" isn't working.  The redis library doesn't support the wildcard pattern when using SUBSCRIBE.  To use wildcards I believe you have to use PSUBSCRIBE (and then handle the PMESSAGE callback).

I expanded the "juggernaut:*" wildcard pattern to "juggernaut:subscribe" & "juggernaut"unsubscribe" and now the example is working.

Thanks!

### CODE REVIEW

**Comment by maccman** [comment]
Ah that's weird, I'm pretty sure wildcards used to work with subscribe, but from the docs it looks like you're correct. The reason for the wild card, rather than the explicit :subscribe or :unsubscribe, is custom events (see events.js). Maybe it would be better to just use psubscribe with the wildcard?

**Comment by mikedemers** [comment]
Ah, good point.  It looks like the custom events are all contained under the "juggernaut:custom" key so you could just add that to the subscribe call alongside "juggernaut:subscribe" and "juggernaut:unsubscribe".

The pattern-based calls will also work but they do have a different callback signature.  I believe they use 3 params rather than 2 (they include the pattern that matched first followed by the same 2 other params).

Thanks!

**Comment by maccman** [comment]
Are you sure this is an  issue? Just tried it and it works fine. What version of Redis and redis.rb are you using?

**Comment by mikedemers** [comment]
I just tried to subscribe with both the original and the modified versions and I can confirm that I'm definitely seeing the issue here.

I'm using very recent builds of redis and redis-rb:

```
$ redis-server --version
Redis server version 2.0.4

$ gem list | grep redis
redis (2.1.1)

$ ruby -v
ruby 1.8.7 (2009-06-12 patchlevel 174) [universal-darwin10.0]

$ uname -v
Darwin Kernel Version 10.5.0: Fri Nov  5 23:20:39 PDT 2010; root:xnu-1504.9.17~1/RELEASE_I386
```

**Comment by maccman** [comment]
Ok, thanks for raising this - committed :)

**Pull request closed without merging**
