### PR TITLE
Updated socket.io dependency to use the latest (0.8.7) version.

### PR DESCRIPTION
**Pull request by dinjas**
Updated socket.io dependency to use the latest (0.8.7) version. This resolved an issue with websockets and Chrome 16 on mac.

### CODE REVIEW

**Comment by maccman** [comment]
What issue is that?

**Comment by dinjas** [comment]
Seemed to be this one: https://github.com/maccman/juggernaut/issues/94
To elaborate a little, Chrome has been unable to make a websocket connection for me and keeps reverting to an XHR connection. Works fine in all other browsers that I've tested.

**Comment by conanbatt** [comment]
I'd appreciate a version bump. The latest socket.io update includes a pretty important fix (https://github.com/LearnBoost/socket.io/issues/602) that right now is killing my production server.

**Comment by kevzettler** [comment]
+1 for the version bump. Same issues as @conanbatt . This is an important hotfix

**Comment by maccman** [comment]
Been trying to update it, but am having trouble running master - can you guys test master.

**Comment by kevzettler** [comment]
If I clone master how can I install the dependencies? does NPM have something to read a local package.json? or do I have to manually install them?

**Comment by conanbatt** [comment]
Yeah, same as @kevzettler . Im not familiar at all with juggernaut's internals. Would like to help more than be a nuisance, maybe there's a TODO here for some documentation on helping with the project.

**Comment by maccman** [comment]
npm install .

**Comment by kevzettler** [comment]
Thanks @maccman 

I just cloned it and started it up in production. Fixes the issue for me. Looks good.

I ran it through node using a relative path to server.js and not the global juggernaut executable. If thats a test case concern.

**Comment by maccman** [comment]
Ok, seems to be working fine now. Not sure what the issue was before. Thanks guys! Released.

**Pull request merged**
